- name: k8s_pre_setup
  hosts: k8s_node
  become_user: root
  remote_user: vt_admin
  become: yes
  gather_facts: no

  tasks:
    - name: k8s_pre_setup
      include_role:
        name: k8s_pre_setup
